export interface SubTask {
  id: string;
  title: string;
  isCompleted: boolean;
  estimatedMinutes: number;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  deadline: string; // YYYY-MM-DD string
  priority: 'low' | 'medium' | 'high' | 'critical' | 'guardian-priority';
  category: string; // e.g. 'Work', 'Personal', 'Study', 'Health'
  estimatedHours: number;
  status: 'pending' | 'in_progress' | 'completed' | 'overdue';
  riskScore: number; // 0 to 100 estimated by AI, or 0 if not calculated
  riskExplanation: string; // generated by AI
  suggestedMitigation: string; // generated by AI
  subtasks: SubTask[];
  createdAt: string;
}

export interface ScheduledItem {
  timeSlot: string; // e.g. "09:00 - 10:30"
  taskId: string;
  taskTitle: string;
  activity: string;
}

export interface DailyActionPlan {
  date: string;
  summary: string;
  focusMessage: string;
  scheduledItems: ScheduledItem[];
  mitigationTips: string[];
}

export interface PriorityRecommendation {
  taskId: string;
  recommendedPriority: 'low' | 'medium' | 'high' | 'critical' | 'guardian-priority';
  priorityReasoning: string;
}

export interface MotivationData {
  quote: string;
  primaryObjective: string;
  biggestRisk: string;
  recommendedAction: string;
}

export interface Habit {
  id: string;
  title: string;
  streak: number;
  lastCompletedDate: string | null; // YYYY-MM-DD
  history: string[]; // dates completed e.g. "2026-06-25"
  category: "Work" | "Study" | "Personal" | "Health" | "Other";
  createdAt: string;
}

